[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

[build.environment]
  VITE_SUPABASE_URL = "https://ixeumchjsmrbzimzmffc.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4ZXVtY2hqc21yYnppbXptZmZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE4MDQ0NzgsImV4cCI6MjA0NzM4MDQ3OH0.FLApJSciiNPCuLwrD-bag1Aw6V1VZhH4cg-j5UpGUj8"
  VITE_VAPID_PUBLIC_KEY = "BIN_hOjuPVZZotveS7RSu1P4dbnEb0m8-A9qQE7UzNv9c-OwLcvsRZdWR88dv0XJTTSsnmc136ZBnekUnQzXz9w"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''