[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://ixeumchjsmrbzimzmffc.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4ZXVtY2hqc21yYnppbXptZmZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE4MDQ0NzgsImV4cCI6MjA0NzM4MDQ3OH0.FLApJSciiNPCuLwrD-bag1Aw6V1VZhH4cg-j5UpGUj8"
  VITE_VAPID_PUBLIC_KEY = "BIN_hOjuPVZZotveS7RSu1P4dbnEb0m8-A9qQE7UzNv9c-OwLcvsRZdWR88dv0XJTTSsnmc136ZBnekUnQzXz9w"
  VITE_TICKET_ENCRYPTION_KEY = "eventlynk-secure-ticket-key-2024"
  STRIPE_PUBLISHABLE_KEY = "pk_test_51QMgG6H93RHd3m5ridrjf6Qq1VDe8AcYVXkqHNrYTkHvmL8NxiMqxiTrw7sYp2NJ8oell5DyB8qoKTb6totw6LRE00D2SoP2G7"
  STRIPE_SECRET_KEY = "sk_test_51QMgG6H93RHd3m5rgHRoNWCTrRAoDH0pItqtiE1YL4tpvS9F3u8qKwCZgLlHCJQkQrtsKMrNMJYXgRtvS9XJcrOS00PO8uoRgY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/storage/*"
  to = "https://ixeumchjsmrbzimzmffc.supabase.co/storage/v1/object/public/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://api.fontshare.com https://m.stripe.network; style-src 'self' 'unsafe-inline' https://api.fontshare.com; img-src 'self' data: https: https://ixeumchjsmrbzimzmffc.supabase.co; connect-src 'self' https: wss: https://ixeumchjsmrbzimzmffc.supabase.co"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Expose-Headers = "Content-Length, X-Requested-With"

[[headers]]
  for = "/storage/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"